/**
 * HIWAYTI Firestore Schema Reference
 * Run this script to seed demo data into your Firestore instance
 * Usage: node seedFirestore.js (from backend directory)
 */
const admin = require('firebase-admin');

// Initialize with service account key
const serviceAccount = require('./serviceAccountKey.json');
admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

// ─── PROVIDERS SEED DATA ─────────────────────────────────────────────────────
const providers = [
  {
    id: 'provider_surf_asilah',
    name: 'Asilah Surf Club',
    role: 'provider',
    category: 'surf',
    commune: 'Asilah',
    communeId: 'commune_asilah',
    rating: 4.8,
    reviewCount: 127,
    bookingCount: 342,
    price: 350,
    priceUnit: '/session',
    maxParticipants: 8,
    verified: true,
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    description: 'Le meilleur club de surf du nord du Maroc. Cours pour tous niveaux, matériel inclus, instructeurs certifiés ISA.',
    location: new admin.firestore.GeoPoint(35.4650, -6.0340),
    phone: '+212 661 234 567',
    email: 'contact@asilahsurf.ma',
    schedule: { 'Lun-Ven': '08:00 - 18:00', 'Sam-Dim': '07:00 - 20:00' },
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'provider_padel_marrakech',
    name: 'Padel Royal Marrakech',
    role: 'provider',
    category: 'padel',
    commune: 'Marrakech',
    communeId: 'commune_marrakech',
    rating: 4.7,
    reviewCount: 89,
    bookingCount: 215,
    price: 280,
    priceUnit: '/heure',
    maxParticipants: 4,
    verified: true,
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
    description: '6 courts premium, éclairage nocturne, vestiaires, restaurant. Club certifié FRP.',
    location: new admin.firestore.GeoPoint(31.6295, -7.9811),
    phone: '+212 524 000 123',
    schedule: { 'Quotidien': '07:00 - 23:00' },
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'provider_hiking_atlas',
    name: 'Atlas Trek & Guide',
    role: 'provider',
    category: 'hiking',
    commune: 'Imlil',
    communeId: 'commune_imlil',
    rating: 4.9,
    reviewCount: 204,
    bookingCount: 456,
    price: 450,
    priceUnit: '/jour',
    maxParticipants: 12,
    verified: true,
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    description: 'Guides certifiés pour le Toubkal, treks personnalisés, bivouac, mules disponibles.',
    location: new admin.firestore.GeoPoint(31.1357, -7.9190),
    phone: '+212 662 987 654',
    schedule: { 'Toute l\'année': 'Sur réservation' },
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'artisan_pottery_fes',
    name: 'Maître Hassan — Poterie de Fès',
    role: 'artisan',
    category: 'pottery',
    commune: 'Fès',
    communeId: 'commune_fes',
    rating: 4.9,
    reviewCount: 312,
    bookingCount: 198,
    price: 200,
    priceUnit: '/atelier',
    maxParticipants: 6,
    verified: true,
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800',
    description: 'Descendant d\'une famille de potiers depuis 7 générations. Ateliers de poterie traditionnelle en zellige et khabia.',
    location: new admin.firestore.GeoPoint(34.0525, -4.9998),
    phone: '+212 535 000 789',
    schedule: { 'Mar-Dim': '09:00 - 17:00' },
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'artisan_leather_marrakech',
    name: 'Tannerie Chouara Artisans',
    role: 'artisan',
    category: 'leather',
    commune: 'Marrakech',
    communeId: 'commune_marrakech',
    rating: 4.6,
    reviewCount: 178,
    bookingCount: 89,
    price: 150,
    priceUnit: '/visite',
    verified: true,
    featured: false,
    coverImage: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800',
    description: 'Maroquinerie artisanale 100% cuir naturel. Sacs, ceintures, babouches. Expédition internationale.',
    location: new admin.firestore.GeoPoint(31.6350, -7.9890),
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
];

// ─── PRODUCTS SEED DATA ───────────────────────────────────────────────────────
const products = [
  {
    id: 'product_tajine_fes',
    name: 'Tajine en Poterie Bleue de Fès',
    artisanId: 'artisan_pottery_fes',
    artisanName: 'Maître Hassan',
    category: 'pottery',
    price: 450,
    rating: 4.9,
    reviewCount: 87,
    available: true,
    soldCount: 234,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400',
    description: 'Tajine artisanal peint à la main, motifs géométriques traditionnels de Fès.',
    communeId: 'commune_fes',
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'product_bag_marrakech',
    name: 'Sac en Cuir Berbère — Cognac',
    artisanId: 'artisan_leather_marrakech',
    artisanName: 'Tannerie Chouara',
    category: 'leather',
    price: 1200,
    rating: 4.8,
    reviewCount: 56,
    available: true,
    soldCount: 123,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
    description: 'Sac à main en cuir véritable tanné naturellement, broderie berbère à la main.',
    communeId: 'commune_marrakech',
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'product_kilim_azilal',
    name: 'Kilim Azilal Authentique',
    artisanId: 'artisan_textile_azilal',
    artisanName: 'Fatima Ait Benhaddou',
    category: 'textiles',
    price: 2800,
    rating: 5.0,
    reviewCount: 34,
    available: true,
    soldCount: 67,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    description: 'Kilim tissé à la main par des femmes de la tribu Ait Benhaddou. Motifs berbères uniques.',
    communeId: 'commune_azilal',
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
];

// ─── COMMUNES SEED DATA ───────────────────────────────────────────────────────
const communes = [
  { id: 'commune_marrakech', name: 'Marrakech', region: 'Marrakech-Safi', population: 959000, rating: 4.7, activeProviders: 142, coverImage: 'https://images.unsplash.com/photo-1570101945621-945409a6370f?w=800', location: new admin.firestore.GeoPoint(31.6295, -7.9811) },
  { id: 'commune_fes', name: 'Fès', region: 'Fès-Meknès', population: 1150000, rating: 4.8, activeProviders: 98, coverImage: 'https://images.unsplash.com/photo-1597825026743-41bbd9e56ab4?w=800', location: new admin.firestore.GeoPoint(34.0525, -4.9998) },
  { id: 'commune_casablanca', name: 'Casablanca', region: 'Casablanca-Settat', population: 3359000, rating: 4.4, activeProviders: 210, coverImage: 'https://images.unsplash.com/photo-1563806283-bc2ebbb540ae?w=800', location: new admin.firestore.GeoPoint(33.5731, -7.5898) },
  { id: 'commune_rabat', name: 'Rabat', region: 'Rabat-Salé-Kénitra', population: 577000, rating: 4.5, activeProviders: 95, coverImage: 'https://images.unsplash.com/photo-1532057793574-d4f77c38cbe2?w=800', location: new admin.firestore.GeoPoint(34.0209, -6.8416) },
  { id: 'commune_tanger', name: 'Tanger', region: 'Tanger-Tétouan-Al Hoceïma', population: 947000, rating: 4.7, activeProviders: 125, coverImage: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800', location: new admin.firestore.GeoPoint(35.7595, -5.8340) },
  { id: 'commune_agadir', name: 'Agadir', region: 'Souss-Massa', population: 421000, rating: 4.6, activeProviders: 110, coverImage: 'https://images.unsplash.com/photo-1583492582987-a2f0eb34b5c7?w=800', location: new admin.firestore.GeoPoint(30.4278, -9.5981) },
  { id: 'commune_essaouira', name: 'Essaouira', region: 'Marrakech-Safi', population: 77000, rating: 4.8, activeProviders: 85, coverImage: 'https://images.unsplash.com/photo-1587395015842-8356cc5b36bd?w=800', location: new admin.firestore.GeoPoint(31.5085, -9.7595) },
  { id: 'commune_chefchaouen', name: 'Chefchaouen', region: 'Tanger-Tétouan-Al Hoceïma', population: 42000, rating: 4.9, activeProviders: 56, coverImage: 'https://images.unsplash.com/photo-1549405436-1e0e854fa4fb?w=800', location: new admin.firestore.GeoPoint(35.1716, -5.2697) },
  { id: 'commune_ouarzazate', name: 'Ouarzazate', region: 'Drâa-Tafilalet', population: 71000, rating: 4.7, activeProviders: 65, coverImage: 'https://images.unsplash.com/photo-1587235287012-de54efcbf018?w=800', location: new admin.firestore.GeoPoint(30.9189, -6.8934) },
  { id: 'commune_dakhla', name: 'Dakhla', region: 'Dakhla-Oued Ed-Dahab', population: 106000, rating: 4.9, activeProviders: 45, coverImage: 'https://images.unsplash.com/photo-1594589255676-e1e7fbcb8e13?w=800', location: new admin.firestore.GeoPoint(23.7145, -15.9388) },
  { id: 'commune_el_jadida', name: 'El Jadida', region: 'Casablanca-Settat', population: 220000, rating: 4.6, activeProviders: 40 },
  { id: 'commune_kenitra', name: 'Kénitra', region: 'Rabat-Salé-Kénitra', population: 431000, rating: 4.3, activeProviders: 35 },
  { id: 'commune_meknes', name: 'Meknès', region: 'Fès-Meknès', population: 635000, rating: 4.6, activeProviders: 55 },
  { id: 'commune_tetouan', name: 'Tétouan', region: 'Tanger-Tétouan-Al Hoceïma', population: 380000, rating: 4.7, activeProviders: 48 },
  { id: 'commune_nador', name: 'Nador', region: 'Oriental', population: 161000, rating: 4.4, activeProviders: 22 },
  { id: 'commune_oujda', name: 'Oujda', region: 'Oriental', population: 494000, rating: 4.3, activeProviders: 30 },
  { id: 'commune_safi', name: 'Safi', region: 'Marrakech-Safi', population: 308000, rating: 4.5, activeProviders: 28 },
  { id: 'commune_mohammedia', name: 'Mohammédia', region: 'Casablanca-Settat', population: 208000, rating: 4.4, activeProviders: 32 },
  { id: 'commune_beni_mellal', name: 'Béni Mellal', region: 'Béni Mellal-Khénifra', population: 192000, rating: 4.5, activeProviders: 18 },
  { id: 'commune_khouribga', name: 'Khouribga', region: 'Béni Mellal-Khénifra', population: 196000, rating: 4.2, activeProviders: 12 },
  { id: 'commune_ifrane', name: 'Ifrane', region: 'Fès-Meknès', population: 15000, rating: 4.9, activeProviders: 45, coverImage: 'https://images.unsplash.com/photo-1548625361-195fe01823ff?w=800' },
  { id: 'commune_taza', name: 'Taza', region: 'Fès-Meknès', population: 148000, rating: 4.4, activeProviders: 15 },
  { id: 'commune_taroudant', name: 'Taroudant', region: 'Souss-Massa', population: 80000, rating: 4.7, activeProviders: 25 },
  { id: 'commune_tiznit', name: 'Tiznit', region: 'Souss-Massa', population: 73000, rating: 4.6, activeProviders: 20 },
  { id: 'commune_al_hoceima', name: 'Al Hoceïma', region: 'Tanger-Tétouan-Al Hoceïma', population: 56000, rating: 4.8, activeProviders: 18 },
  { id: 'commune_larache', name: 'Larache', region: 'Tanger-Tétouan-Al Hoceïma', population: 125000, rating: 4.4, activeProviders: 14 },
  { id: 'commune_khemisset', name: 'Khémisset', region: 'Rabat-Salé-Kénitra', population: 131000, rating: 4.1, activeProviders: 8 },
  { id: 'commune_settat', name: 'Settat', region: 'Casablanca-Settat', population: 142000, rating: 4.2, activeProviders: 10 },
  { id: 'commune_berrechid', name: 'Berrechid', region: 'Casablanca-Settat', population: 136000, rating: 4.1, activeProviders: 7 },
  { id: 'commune_guelmim', name: 'Guelmim', region: 'Guelmim-Oued Noun', population: 118000, rating: 4.5, activeProviders: 12 },
  { id: 'commune_midelt', name: 'Midelt', region: 'Drâa-Tafilalet', population: 55000, rating: 4.6, activeProviders: 22 },
  { id: 'commune_errachidia', name: 'Errachidia', region: 'Drâa-Tafilalet', population: 92000, rating: 4.5, activeProviders: 15 },
  { id: 'commune_khenifra', name: 'Khénifra', region: 'Béni Mellal-Khénifra', population: 117000, rating: 4.4, activeProviders: 20 },
  { id: 'commune_azrou', name: 'Azrou', region: 'Fès-Meknès', population: 54000, rating: 4.8, activeProviders: 28 },
  { id: 'commune_boujdour', name: 'Boujdour', region: 'Laâyoune-Sakia El Hamra', population: 45000, rating: 4.4, activeProviders: 6 },
  { id: 'commune_laayoune', name: 'Laâyoune', region: 'Laâyoune-Sakia El Hamra', population: 217000, rating: 4.3, activeProviders: 18 },
  { id: 'commune_tan_tan', name: 'Tan-Tan', region: 'Guelmim-Oued Noun', population: 73000, rating: 4.2, activeProviders: 8 },
  { id: 'commune_sidi_ifni', name: 'Sidi Ifni', region: 'Guelmim-Oued Noun', population: 20000, rating: 4.7, activeProviders: 12 },
];

// ─── ACTIVITIES SEED DATA ─────────────────────────────────────────────────────
const activities = [
  {
    id: 'act_surf_debutant_asilah',
    name: 'Cours de Surf Débutants',
    providerId: 'provider_surf_asilah',
    communeId: 'commune_asilah',
    placeId: 'place_asilah_beach',
    category: 'surf',
    type: 'course',
    price: 350,
    priceUnit: 'personne',
    duration: '2h',
    minParticipants: 1,
    maxParticipants: 6,
    difficulty: 'Débutant',
    languages: ['Français', 'English', 'العربية'],
    description: 'Cours complet pour débutants : théorie, sécurité, pratique en eau calme puis vagues.',
    included: ['Combinaison', 'Planche', 'Instructeur certifié ISA', 'Assurance'],
    excluded: ['Transport', 'Repas'],
    requirements: ['Savoir nager', 'Minimum 8 ans'],
    meetingPoint: 'Parking de la plage Asilah Nord',
    active: true,
    bookingCount: 142,
    rating: 4.8,
    reviewCount: 87,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'act_surf_advanced_asilah',
    name: 'Session Surf Avancé',
    providerId: 'provider_surf_asilah',
    communeId: 'commune_asilah',
    placeId: 'place_asilah_beach',
    category: 'surf',
    type: 'session',
    price: 250,
    priceUnit: 'personne',
    duration: '3h',
    minParticipants: 1,
    maxParticipants: 4,
    difficulty: 'Avancé',
    languages: ['Français', 'English'],
    description: 'Session libre avec analyse vidéo. Accès aux spots secrets d\'Asilah.',
    included: ['Planche longboard ou shortboard au choix', 'Analyse vidéo'],
    excluded: ['Combinaison (location disponible)'],
    requirements: ['Niveau intermédiaire minimum', 'Maîtrise du take-off'],
    active: true,
    bookingCount: 89,
    rating: 4.9,
    reviewCount: 54,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'act_padel_lesson_marrakech',
    name: 'Cours de Padel — Initiation',
    providerId: 'provider_padel_marrakech',
    communeId: 'commune_marrakech',
    placeId: 'place_marrakech_padel',
    category: 'padel',
    type: 'course',
    price: 280,
    priceUnit: 'heure',
    duration: '1h30',
    minParticipants: 2,
    maxParticipants: 4,
    difficulty: 'Débutant',
    languages: ['Français', 'العربية', 'English'],
    description: 'Leçon d\'initiation au padel avec coach certifié FRP.',
    included: ['Court', 'Raquettes', 'Balles', 'Coach'],
    excluded: ['Eau', 'Serviette'],
    active: true,
    bookingCount: 215,
    rating: 4.7,
    reviewCount: 89,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'act_trek_toubkal_imlil',
    name: 'Ascension Jbel Toubkal',
    providerId: 'provider_hiking_atlas',
    communeId: 'commune_imlil',
    placeId: 'place_imlil_trailhead',
    category: 'hiking',
    type: 'tour',
    price: 900,
    priceUnit: 'personne',
    duration: '2 jours',
    minParticipants: 2,
    maxParticipants: 8,
    difficulty: 'Avancé',
    languages: ['Français', 'English', 'Español'],
    description: 'Ascension du plus haut sommet d\'Afrique du Nord (4167m). Nuitée au refuge Toubkal.',
    included: ['Guide certifié', 'Mule pour bagages', 'Nuitée refuge', 'Repas du soir et petit-déjeuner'],
    excluded: ['Équipement personnel', 'Assurance trek'],
    requirements: ['Bonne condition physique', 'Expérience randonnée', 'Équipement montagne'],
    meetingPoint: 'Village d\'Imlil, Place principale',
    active: true,
    bookingCount: 456,
    rating: 4.9,
    reviewCount: 204,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
  {
    id: 'act_pottery_workshop_fes',
    name: 'Atelier Poterie Traditionnelle',
    providerId: 'artisan_pottery_fes',
    communeId: 'commune_fes',
    placeId: 'place_fes_medina',
    category: 'pottery',
    type: 'workshop',
    price: 200,
    priceUnit: 'personne',
    duration: '3h',
    minParticipants: 1,
    maxParticipants: 6,
    difficulty: 'Débutant',
    languages: ['Français', 'English', 'العربية'],
    description: 'Façonnage, décoration zellige et khabia. Cuisson au four traditionnel. Pièce repartie avec vous.',
    included: ['Matériaux', 'Tablier', 'Thé à la menthe', 'Pièce réalisée'],
    excluded: ['Transport depuis la ville nouvelle'],
    meetingPoint: 'Riad Maître Hassan, Rue Chouara, Médina de Fès',
    active: true,
    bookingCount: 198,
    rating: 4.9,
    reviewCount: 312,
    createdAt: admin.firestore.FieldValue.serverTimestamp(),
  },
];

// ─── PLACES SEED DATA ─────────────────────────────────────────────────────────
const places = [
  {
    id: 'place_asilah_beach',
    name: 'Plage d\'Asilah',
    communeId: 'commune_asilah',
    region: 'Tanger-Tétouan-Al Hoceïma',
    category: 'surf',
    description: 'Plage de sable fin, vagues idéales pour le surf, eaux claires.',
    location: new admin.firestore.GeoPoint(35.4650, -6.0340),
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    visitorCount: 0,
    activitiesCount: 2,
    providersCount: 1,
  },
  {
    id: 'place_marrakech_padel',
    name: 'Palmeraie Tennis & Padel',
    communeId: 'commune_marrakech',
    region: 'Marrakech-Safi',
    category: 'padel',
    description: '6 courts de padel premium en plein air, éclairés.',
    location: new admin.firestore.GeoPoint(31.6295, -7.9811),
    coverImage: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800',
    visitorCount: 0,
    activitiesCount: 1,
    providersCount: 1,
  },
  {
    id: 'place_imlil_trailhead',
    name: 'Départ Imlil — Toubkal',
    communeId: 'commune_imlil',
    region: 'Marrakech-Safi',
    category: 'hiking',
    description: 'Point de départ officiel pour l\'ascension du Jbel Toubkal.',
    location: new admin.firestore.GeoPoint(31.1357, -7.9190),
    coverImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    visitorCount: 0,
    activitiesCount: 1,
    providersCount: 1,
  },
  {
    id: 'place_fes_medina',
    name: 'Médina de Fès — Quartier Artisanal',
    communeId: 'commune_fes',
    region: 'Fès-Meknès',
    category: 'pottery',
    description: 'Le cœur artisanal de la médina de Fès, classée UNESCO.',
    location: new admin.firestore.GeoPoint(34.0525, -4.9998),
    coverImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800',
    visitorCount: 0,
    activitiesCount: 1,
    providersCount: 1,
  },
  {
    id: 'place_essaouira_kite',
    name: 'Spot Kitesurf Essaouira',
    communeId: 'commune_essaouira',
    region: 'Marrakech-Safi',
    category: 'surf',
    description: 'Spot mondial de kitesurf, vent constant de l\'Alizé.',
    location: new admin.firestore.GeoPoint(31.5085, -9.7595),
    coverImage: 'https://images.unsplash.com/photo-1587395015842-8356cc5b36bd?w=800',
    visitorCount: 0,
    activitiesCount: 0,
    providersCount: 0,
  },
  {
    id: 'place_dakhla_lagoon',
    name: 'Lagune de Dakhla',
    communeId: 'commune_dakhla',
    region: 'Dakhla-Oued Ed-Dahab',
    category: 'surf',
    description: 'Lagune turquoise, spot mondial de windsurf et kitesurf.',
    location: new admin.firestore.GeoPoint(23.7145, -15.9388),
    coverImage: 'https://images.unsplash.com/photo-1594589255676-e1e7fbcb8e13?w=800',
    visitorCount: 0,
    activitiesCount: 0,
    providersCount: 0,
  },
];

// ─── RUN SEED ─────────────────────────────────────────────────────────────────
async function seed() {
  console.log('🌍 Seeding HIWAYTI Firestore...');

  // Firestore batch has 500-write limit; split into chunks
  const allWrites = [
    ...providers.map(p => ({ col: 'providers', ...p })),
    ...products.map(p => ({ col: 'products', ...p })),
    ...communes.map(c => ({ col: 'communes', ...c })),
    ...activities.map(a => ({ col: 'activities', ...a })),
    ...places.map(p => ({ col: 'places', ...p })),
  ];

  const CHUNK_SIZE = 400;
  for (let i = 0; i < allWrites.length; i += CHUNK_SIZE) {
    const chunk = allWrites.slice(i, i + CHUNK_SIZE);
    const batch = db.batch();
    chunk.forEach(({ col, id, ...data }) => {
      batch.set(db.collection(col).doc(id), data);
    });
    await batch.commit();
    console.log(`   ✅ Batch ${Math.floor(i / CHUNK_SIZE) + 1} committed (${chunk.length} docs)`);
  }

  console.log(`\n✅ Seed complete:`);
  console.log(`   • ${providers.length} providers`);
  console.log(`   • ${products.length} products`);
  console.log(`   • ${communes.length} communes`);
  console.log(`   • ${activities.length} activities`);
  console.log(`   • ${places.length} places`);
  process.exit(0);
}

seed().catch(err => { console.error('❌ Seed failed:', err); process.exit(1); });

